### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sascha-T**

### CODE REVIEW

**Review by arguiot — CHANGES_REQUESTED** [review]
The concept is here, could you add Travis test, and put badges just under the title?

**Comment by Sascha-T** [comment]
uh, ok, but how would i add the changes to here?

**Comment by arguiot** [comment]
The answer is under your comment:
capture d ecran 2018-01-28 a 18 59 29

**Comment by Sascha-T** [comment]
wow, did not see that, will add travis test and put the badges under the title

**Comment by arguiot** [comment]
Ok

**Review by arguiot — APPROVED** [review]

**Pull request merged**
